export const REVIEWS_DATA: ReviewData[] = [
  {
    date: "12.05.2023",
    rating: 4,
    message: `Я хотел бы поделиться своим положительным опытом перевозки моего дорогого четвероногого друга. В последнее время мне понадобилось отправить своего питомца в другой город, и после долгих поисков я обратился в компанию "Pets Transport".С самого начала мне было приятно общаться с сотрудниками этой компании. Они были внимательны, отзывчивы и готовы ответить на все мои вопросы и опасения. Компания предоставила всю необходимую информацию о процессе перевозки и просветила меня по всем правилам и требованиям.`,
    name: "Константин",
    pet: "Кот Василий",
    image: "/images/mad_cat.png",
  },
  {
    date: "12.05.2023",
    rating: 5,
    message: `Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.`,
    name: "Константин",
    pet: "Константин",
    image: "/images/mad_cat.png",
  },
  {
    date: "12.05.2023",
    rating: 0,
    message: `Я хотел бы поделиться своим положительным опытом перевозки моего дорогого четвероногого друга. В последнее время мне понадобилось отправить своего питомца в другой город, и после долгих поисков я обратился в компанию "Pets Transport".С самого начала мне было приятно общаться с сотрудниками этой компании. Они были внимательны, отзывчивы и готовы ответить на все мои вопросы и опасения. Компания предоставила всю необходимую информацию о процессе перевозки и просветила меня по всем правилам и требованиям.`,
    name: "Константин",
    pet: "ШОКОЛАДКА",
    image: "/images/mad_cat.png",
  },
  {
    date: "12.05.2023",
    rating: 2,
    message: `Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.`,
    name: "Константин",
    pet: "Кот Василий",
    image: "/images/mad_cat.png",
  },
  {
    date: "12.05.2023",
    rating: 4,
    message: `Я хотел бы поделиться своим положительным опытом перевозки моего дорогого четвероногого друга. В последнее время мне понадобилось отправить своего питомца в другой город, и после долгих поисков я обратился в компанию "Pets Transport".С самого начала мне было приятно общаться с сотрудниками этой компании. Они были внимательны, отзывчивы и готовы ответить на все мои вопросы и опасения. Компания предоставила всю необходимую информацию о процессе перевозки и просветила меня по всем правилам и требованиям.`,
    name: "Константин",
    pet: "Кот Василий",
    image: "/images/mad_cat.png",
  },
  {
    date: "12.05.2023",
    rating: 3,
    message: `Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.`,
    name: "Константин",
    pet: "Кот Василий",
    image: "/images/mad_cat.png",
  },
];
